### PR TITLE
Bit 1 was not taking custom format values so added conditional refere…

### PR DESCRIPTION
**Pull request by kunalkaskar**
Bit 1 was not taking custom format values so added conditional reference to custom format

### CODE REVIEW

**Comment by kunalkaskar** [comment]
@zemuldo Can you please create bugfix release in next couple of days for this change?

**Comment by zemuldo** [comment]
Sure! I working on that. Should be available tomorrow.

**Comment by zemuldo** [comment]
You can also place a review on the PR below for me as its blocking the current release. I am trying to make the code more readable, maintainable and documented for other guys to manage. 
https://github.com/zemuldo/iso_8583/pull/57

**Comment by kunalkaskar** [comment]
> You can also place a review on the PR below for me as its blocking the current release. I am trying to make the code more readable, maintainable and documented for other guys to manage.
> #57

Sure I will look into the PR. I will review it in next 24hours

**Comment by zemuldo** [comment]
I had to merge it though.

**Comment by zemuldo** [comment]
@kunalkaskar Version 2.6.4 should have the feature. Current latest on NPM

**Pull request merged**
